### PR TITLE
Requesting approval for the models, tests and database implementation.

### PR DESCRIPTION
**Pull request by stratospherique**

### CODE REVIEW

**Comment by stratospherique** [comment]
The ER diagram is in the README file

**Review by inhaq — CHANGES_REQUESTED** [review]
Hi Team,
Great start to the final project. Nice to have some planning before the project and ERD is one of the options which is very important. You're on the right path.
Just to clear some things in ERD, if `user` has many `post` and `user` has many `likes`, it'll not make sense. `User` can't do like directly without creating `post` so it should be only between `post` has many `likes` in ERD. Kindly make update, wherever necessary.
Kindly resubmit once updated. Thanks

**Review by inhaq — CHANGES_REQUESTED** [review]
I think I didn't explain it well as the changes aren't done properly. I'll try my best to explain it in simple steps. If need further guidance, please don't hesitate to reach me on slack.
 - Go to [draw.io](https://www.draw.io/)
 - Select `create new diagram`, then `Software` and within `Software` select the last one which is `ERD`
 - Click on `create`
 - Now a bit about technicalities of ERD
 - ERD is basically for database design and it's not random diagram to brainstorm
 - You'll need to choose `primary keys` and `foreign keys` in each table
 - Each relationship depends on whether it has anything directly related to it
 - Let's say in our case, User will first create `post` and then `comment` on it, here we'll make the relationship of `User` with only `Post` and then relation  of `Post` with `comment`, there is no direct relation of comment with User.

I hope it'll make it a bit clear. Let's make these updates and resubmit.

**Review by inhaq — APPROVED** [review]
Good job, Team
It's 👍🏻for the ERD, let's move on to the next part of the project.

**Review by inhaq — CHANGES_REQUESTED** [review]
Awesome, let's add `dependent: destroy` where it's required. If the user deletes Post, it should delete comments, etc.
Once updated, kindly resubmit for review.

**Review by inhaq — APPROVED** [review]
Well done, let's move on to the next step of the project 👍🏻

**Pull request closed without merging**
